title: "MetaPhage"
subtitle: "A nextflow pipeline for phage discovery."
intro_text: "This is the main report for MetapHage."
report_comment: "This is a comment about this report."
custom_logo: './logo_tmp.png'